// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyProto.proto

#include "MyProto.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace MyPackage {

inline constexpr FileUploadResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : cacheid_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileUploadResponse::FileUploadResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileUploadResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileUploadResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileUploadResponseDefaultTypeInternal() {}
  union {
    FileUploadResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileUploadResponseDefaultTypeInternal _FileUploadResponse_default_instance_;

inline constexpr FileUploadRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : chunk_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        size_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR FileUploadRequest::FileUploadRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileUploadRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileUploadRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileUploadRequestDefaultTypeInternal() {}
  union {
    FileUploadRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileUploadRequestDefaultTypeInternal _FileUploadRequest_default_instance_;

inline constexpr FileSearchRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : condition_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileSearchRequest::FileSearchRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileSearchRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileSearchRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileSearchRequestDefaultTypeInternal() {}
  union {
    FileSearchRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileSearchRequestDefaultTypeInternal _FileSearchRequest_default_instance_;

inline constexpr FileInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fileid_{::int64_t{0}},
        filesize_{::int64_t{0}},
        updatetime_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileInfo::FileInfo(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileInfoDefaultTypeInternal() {}
  union {
    FileInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileInfoDefaultTypeInternal _FileInfo_default_instance_;

inline constexpr FileDownloadResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : chunk_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        size_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR FileDownloadResponse::FileDownloadResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileDownloadResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileDownloadResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileDownloadResponseDefaultTypeInternal() {}
  union {
    FileDownloadResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileDownloadResponseDefaultTypeInternal _FileDownloadResponse_default_instance_;

inline constexpr FileDownloadRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : fileid_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileDownloadRequest::FileDownloadRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileDownloadRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileDownloadRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileDownloadRequestDefaultTypeInternal() {}
  union {
    FileDownloadRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileDownloadRequestDefaultTypeInternal _FileDownloadRequest_default_instance_;

inline constexpr FileSearchResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : infos_{},
        ok_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileSearchResponse::FileSearchResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileSearchResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileSearchResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileSearchResponseDefaultTypeInternal() {}
  union {
    FileSearchResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileSearchResponseDefaultTypeInternal _FileSearchResponse_default_instance_;

inline constexpr FileOperateResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        info_{nullptr},
        ok_{false} {}

template <typename>
PROTOBUF_CONSTEXPR FileOperateResponse::FileOperateResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileOperateResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileOperateResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileOperateResponseDefaultTypeInternal() {}
  union {
    FileOperateResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileOperateResponseDefaultTypeInternal _FileOperateResponse_default_instance_;

inline constexpr FileOperateRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        info_{nullptr},
        cacheid_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR FileOperateRequest::FileOperateRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileOperateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileOperateRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileOperateRequestDefaultTypeInternal() {}
  union {
    FileOperateRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileOperateRequestDefaultTypeInternal _FileOperateRequest_default_instance_;
}  // namespace MyPackage
static ::_pb::Metadata file_level_metadata_MyProto_2eproto[9];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_MyProto_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_MyProto_2eproto = nullptr;
const ::uint32_t TableStruct_MyProto_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileInfo, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileInfo, _impl_.fileid_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileInfo, _impl_.filesize_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileInfo, _impl_.updatetime_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileInfo, _impl_.filename_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileOperateRequest, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileOperateRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileOperateRequest, _impl_.info_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileOperateRequest, _impl_.cacheid_),
    0,
    ~0u,
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileOperateResponse, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileOperateResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileOperateResponse, _impl_.info_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileOperateResponse, _impl_.ok_),
    0,
    ~0u,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileSearchRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileSearchRequest, _impl_.condition_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileSearchResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileSearchResponse, _impl_.infos_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileSearchResponse, _impl_.ok_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileUploadRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileUploadRequest, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileUploadRequest, _impl_.chunk_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileUploadRequest, _impl_.size_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileUploadResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileUploadResponse, _impl_.cacheid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileDownloadRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileDownloadRequest, _impl_.fileid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileDownloadResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileDownloadResponse, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileDownloadResponse, _impl_.chunk_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileDownloadResponse, _impl_.size_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::MyPackage::FileInfo)},
        {12, 22, -1, sizeof(::MyPackage::FileOperateRequest)},
        {24, 34, -1, sizeof(::MyPackage::FileOperateResponse)},
        {36, -1, -1, sizeof(::MyPackage::FileSearchRequest)},
        {45, -1, -1, sizeof(::MyPackage::FileSearchResponse)},
        {55, -1, -1, sizeof(::MyPackage::FileUploadRequest)},
        {67, -1, -1, sizeof(::MyPackage::FileUploadResponse)},
        {76, -1, -1, sizeof(::MyPackage::FileDownloadRequest)},
        {85, -1, -1, sizeof(::MyPackage::FileDownloadResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::MyPackage::_FileInfo_default_instance_._instance,
    &::MyPackage::_FileOperateRequest_default_instance_._instance,
    &::MyPackage::_FileOperateResponse_default_instance_._instance,
    &::MyPackage::_FileSearchRequest_default_instance_._instance,
    &::MyPackage::_FileSearchResponse_default_instance_._instance,
    &::MyPackage::_FileUploadRequest_default_instance_._instance,
    &::MyPackage::_FileUploadResponse_default_instance_._instance,
    &::MyPackage::_FileDownloadRequest_default_instance_._instance,
    &::MyPackage::_FileDownloadResponse_default_instance_._instance,
};
const char descriptor_table_protodef_MyProto_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rMyProto.proto\022\tMyPackage\"R\n\010FileInfo\022\016"
    "\n\006fileId\030\001 \001(\003\022\020\n\010fileSize\030\002 \001(\003\022\022\n\nupda"
    "teTime\030\003 \001(\003\022\020\n\010fileName\030\004 \001(\t\"H\n\022FileOp"
    "erateRequest\022!\n\004info\030\001 \001(\0132\023.MyPackage.F"
    "ileInfo\022\017\n\007cacheId\030\002 \001(\003\"D\n\023FileOperateR"
    "esponse\022!\n\004info\030\001 \001(\0132\023.MyPackage.FileIn"
    "fo\022\n\n\002ok\030\002 \001(\010\"&\n\021FileSearchRequest\022\021\n\tc"
    "ondition\030\001 \001(\t\"D\n\022FileSearchResponse\022\"\n\005"
    "infos\030\001 \003(\0132\023.MyPackage.FileInfo\022\n\n\002ok\030\002"
    " \001(\010\"S\n\021FileUploadRequest\022\022\n\010fileSize\030\001 "
    "\001(\003H\000\022\023\n\tchunkSize\030\002 \001(\003H\000\022\r\n\005chunk\030\003 \001("
    "\014B\006\n\004size\"%\n\022FileUploadResponse\022\017\n\007cache"
    "Id\030\001 \001(\003\"%\n\023FileDownloadRequest\022\016\n\006fileI"
    "d\030\001 \001(\003\"V\n\024FileDownloadResponse\022\022\n\010fileS"
    "ize\030\001 \001(\003H\000\022\023\n\tchunkSize\030\002 \001(\003H\000\022\r\n\005chun"
    "k\030\003 \001(\014B\006\n\004size2\257\001\n\rMyFileService\022K\n\nupl"
    "oadFile\022\034.MyPackage.FileUploadRequest\032\035."
    "MyPackage.FileUploadResponse(\001\022Q\n\014downlo"
    "adFile\022\036.MyPackage.FileDownloadRequest\032\037"
    ".MyPackage.FileDownloadResponse0\0012\221\003\n\020My"
    "OperateService\022K\n\ninsertFile\022\035.MyPackage"
    ".FileOperateRequest\032\036.MyPackage.FileOper"
    "ateResponse\022K\n\ndeleteFile\022\035.MyPackage.Fi"
    "leOperateRequest\032\036.MyPackage.FileOperate"
    "Response\022K\n\nupdateFile\022\035.MyPackage.FileO"
    "perateRequest\032\036.MyPackage.FileOperateRes"
    "ponse\022K\n\nselectFile\022\035.MyPackage.FileOper"
    "ateRequest\032\036.MyPackage.FileOperateRespon"
    "se\022I\n\nsearchFile\022\034.MyPackage.FileSearchR"
    "equest\032\035.MyPackage.FileSearchResponseb\006p"
    "roto3"
};
static ::absl::once_flag descriptor_table_MyProto_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_MyProto_2eproto = {
    false,
    false,
    1205,
    descriptor_table_protodef_MyProto_2eproto,
    "MyProto.proto",
    &descriptor_table_MyProto_2eproto_once,
    nullptr,
    0,
    9,
    schemas,
    file_default_instances,
    TableStruct_MyProto_2eproto::offsets,
    file_level_metadata_MyProto_2eproto,
    file_level_enum_descriptors_MyProto_2eproto,
    file_level_service_descriptors_MyProto_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_MyProto_2eproto_getter() {
  return &descriptor_table_MyProto_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_MyProto_2eproto(&descriptor_table_MyProto_2eproto);
namespace MyPackage {
// ===================================================================

class FileInfo::_Internal {
 public:
};

FileInfo::FileInfo(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.FileInfo)
}
inline PROTOBUF_NDEBUG_INLINE FileInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : filename_(arena, from.filename_),
        _cached_size_{0} {}

FileInfo::FileInfo(
    ::google::protobuf::Arena* arena,
    const FileInfo& from)
    : ::google::protobuf::Message(arena) {
  FileInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, fileid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, fileid_),
           offsetof(Impl_, updatetime_) -
               offsetof(Impl_, fileid_) +
               sizeof(Impl_::updatetime_));

  // @@protoc_insertion_point(copy_constructor:MyPackage.FileInfo)
}
inline PROTOBUF_NDEBUG_INLINE FileInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_(arena),
        _cached_size_{0} {}

inline void FileInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, fileid_),
           0,
           offsetof(Impl_, updatetime_) -
               offsetof(Impl_, fileid_) +
               sizeof(Impl_::updatetime_));
}
FileInfo::~FileInfo() {
  // @@protoc_insertion_point(destructor:MyPackage.FileInfo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileInfo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.filename_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.FileInfo)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  ::memset(&_impl_.fileid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.updatetime_) -
      reinterpret_cast<char*>(&_impl_.fileid_)) + sizeof(_impl_.updatetime_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileInfo::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 35, 2> FileInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileInfo_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string fileName = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.filename_)}},
    // int64 fileId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileInfo, _impl_.fileid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.fileid_)}},
    // int64 fileSize = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileInfo, _impl_.filesize_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.filesize_)}},
    // int64 updateTime = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileInfo, _impl_.updatetime_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.updatetime_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 fileId = 1;
    {PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.fileid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 fileSize = 2;
    {PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.filesize_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 updateTime = 3;
    {PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.updatetime_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string fileName = 4;
    {PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\0\0\10\0\0\0"
    "MyPackage.FileInfo"
    "fileName"
  }},
};

::uint8_t* FileInfo::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.FileInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 fileId = 1;
  if (this->_internal_fileid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_fileid(), target);
  }

  // int64 fileSize = 2;
  if (this->_internal_filesize() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_filesize(), target);
  }

  // int64 updateTime = 3;
  if (this->_internal_updatetime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_updatetime(), target);
  }

  // string fileName = 4;
  if (!this->_internal_filename().empty()) {
    const std::string& _s = this->_internal_filename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MyPackage.FileInfo.fileName");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.FileInfo)
  return target;
}

::size_t FileInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.FileInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string fileName = 4;
  if (!this->_internal_filename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_filename());
  }

  // int64 fileId = 1;
  if (this->_internal_fileid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_fileid());
  }

  // int64 fileSize = 2;
  if (this->_internal_filesize() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_filesize());
  }

  // int64 updateTime = 3;
  if (this->_internal_updatetime() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_updatetime());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileInfo::_class_data_ = {
    FileInfo::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileInfo::GetClassData() const {
  return &_class_data_;
}

void FileInfo::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileInfo*>(&to_msg);
  auto& from = static_cast<const FileInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.FileInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (from._internal_fileid() != 0) {
    _this->_internal_set_fileid(from._internal_fileid());
  }
  if (from._internal_filesize() != 0) {
    _this->_internal_set_filesize(from._internal_filesize());
  }
  if (from._internal_updatetime() != 0) {
    _this->_internal_set_updatetime(from._internal_updatetime());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileInfo::CopyFrom(const FileInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.FileInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileInfo::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileInfo::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileInfo::InternalSwap(FileInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.updatetime_)
      + sizeof(FileInfo::_impl_.updatetime_)
      - PROTOBUF_FIELD_OFFSET(FileInfo, _impl_.fileid_)>(
          reinterpret_cast<char*>(&_impl_.fileid_),
          reinterpret_cast<char*>(&other->_impl_.fileid_));
}

::google::protobuf::Metadata FileInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[0]);
}
// ===================================================================

class FileOperateRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<FileOperateRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(FileOperateRequest, _impl_._has_bits_);
  static const ::MyPackage::FileInfo& info(const FileOperateRequest* msg);
  static void set_has_info(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::MyPackage::FileInfo& FileOperateRequest::_Internal::info(const FileOperateRequest* msg) {
  return *msg->_impl_.info_;
}
FileOperateRequest::FileOperateRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.FileOperateRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileOperateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

FileOperateRequest::FileOperateRequest(
    ::google::protobuf::Arena* arena,
    const FileOperateRequest& from)
    : ::google::protobuf::Message(arena) {
  FileOperateRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.info_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::MyPackage::FileInfo>(arena, *from._impl_.info_)
                : nullptr;
  _impl_.cacheid_ = from._impl_.cacheid_;

  // @@protoc_insertion_point(copy_constructor:MyPackage.FileOperateRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileOperateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void FileOperateRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, info_),
           0,
           offsetof(Impl_, cacheid_) -
               offsetof(Impl_, info_) +
               sizeof(Impl_::cacheid_));
}
FileOperateRequest::~FileOperateRequest() {
  // @@protoc_insertion_point(destructor:MyPackage.FileOperateRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileOperateRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.info_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileOperateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.FileOperateRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.info_ != nullptr);
    _impl_.info_->Clear();
  }
  _impl_.cacheid_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileOperateRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> FileOperateRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FileOperateRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_FileOperateRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 cacheId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileOperateRequest, _impl_.cacheid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(FileOperateRequest, _impl_.cacheid_)}},
    // .MyPackage.FileInfo info = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(FileOperateRequest, _impl_.info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .MyPackage.FileInfo info = 1;
    {PROTOBUF_FIELD_OFFSET(FileOperateRequest, _impl_.info_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int64 cacheId = 2;
    {PROTOBUF_FIELD_OFFSET(FileOperateRequest, _impl_.cacheid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }}, {{
    {::_pbi::TcParser::GetTable<::MyPackage::FileInfo>()},
  }}, {{
  }},
};

::uint8_t* FileOperateRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.FileOperateRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .MyPackage.FileInfo info = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, _Internal::info(this),
        _Internal::info(this).GetCachedSize(), target, stream);
  }

  // int64 cacheId = 2;
  if (this->_internal_cacheid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_cacheid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.FileOperateRequest)
  return target;
}

::size_t FileOperateRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.FileOperateRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .MyPackage.FileInfo info = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.info_);
  }

  // int64 cacheId = 2;
  if (this->_internal_cacheid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_cacheid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileOperateRequest::_class_data_ = {
    FileOperateRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileOperateRequest::GetClassData() const {
  return &_class_data_;
}

void FileOperateRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileOperateRequest*>(&to_msg);
  auto& from = static_cast<const FileOperateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.FileOperateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_info()->::MyPackage::FileInfo::MergeFrom(
        from._internal_info());
  }
  if (from._internal_cacheid() != 0) {
    _this->_internal_set_cacheid(from._internal_cacheid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileOperateRequest::CopyFrom(const FileOperateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.FileOperateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileOperateRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileOperateRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileOperateRequest::InternalSwap(FileOperateRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileOperateRequest, _impl_.cacheid_)
      + sizeof(FileOperateRequest::_impl_.cacheid_)
      - PROTOBUF_FIELD_OFFSET(FileOperateRequest, _impl_.info_)>(
          reinterpret_cast<char*>(&_impl_.info_),
          reinterpret_cast<char*>(&other->_impl_.info_));
}

::google::protobuf::Metadata FileOperateRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[1]);
}
// ===================================================================

class FileOperateResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<FileOperateResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(FileOperateResponse, _impl_._has_bits_);
  static const ::MyPackage::FileInfo& info(const FileOperateResponse* msg);
  static void set_has_info(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::MyPackage::FileInfo& FileOperateResponse::_Internal::info(const FileOperateResponse* msg) {
  return *msg->_impl_.info_;
}
FileOperateResponse::FileOperateResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.FileOperateResponse)
}
inline PROTOBUF_NDEBUG_INLINE FileOperateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

FileOperateResponse::FileOperateResponse(
    ::google::protobuf::Arena* arena,
    const FileOperateResponse& from)
    : ::google::protobuf::Message(arena) {
  FileOperateResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.info_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::MyPackage::FileInfo>(arena, *from._impl_.info_)
                : nullptr;
  _impl_.ok_ = from._impl_.ok_;

  // @@protoc_insertion_point(copy_constructor:MyPackage.FileOperateResponse)
}
inline PROTOBUF_NDEBUG_INLINE FileOperateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void FileOperateResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, info_),
           0,
           offsetof(Impl_, ok_) -
               offsetof(Impl_, info_) +
               sizeof(Impl_::ok_));
}
FileOperateResponse::~FileOperateResponse() {
  // @@protoc_insertion_point(destructor:MyPackage.FileOperateResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileOperateResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.info_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileOperateResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.FileOperateResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.info_ != nullptr);
    _impl_.info_->Clear();
  }
  _impl_.ok_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileOperateResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> FileOperateResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FileOperateResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_FileOperateResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool ok = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileOperateResponse, _impl_.ok_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(FileOperateResponse, _impl_.ok_)}},
    // .MyPackage.FileInfo info = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(FileOperateResponse, _impl_.info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .MyPackage.FileInfo info = 1;
    {PROTOBUF_FIELD_OFFSET(FileOperateResponse, _impl_.info_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool ok = 2;
    {PROTOBUF_FIELD_OFFSET(FileOperateResponse, _impl_.ok_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }}, {{
    {::_pbi::TcParser::GetTable<::MyPackage::FileInfo>()},
  }}, {{
  }},
};

::uint8_t* FileOperateResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.FileOperateResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .MyPackage.FileInfo info = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, _Internal::info(this),
        _Internal::info(this).GetCachedSize(), target, stream);
  }

  // bool ok = 2;
  if (this->_internal_ok() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_ok(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.FileOperateResponse)
  return target;
}

::size_t FileOperateResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.FileOperateResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .MyPackage.FileInfo info = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.info_);
  }

  // bool ok = 2;
  if (this->_internal_ok() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileOperateResponse::_class_data_ = {
    FileOperateResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileOperateResponse::GetClassData() const {
  return &_class_data_;
}

void FileOperateResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileOperateResponse*>(&to_msg);
  auto& from = static_cast<const FileOperateResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.FileOperateResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_info()->::MyPackage::FileInfo::MergeFrom(
        from._internal_info());
  }
  if (from._internal_ok() != 0) {
    _this->_internal_set_ok(from._internal_ok());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileOperateResponse::CopyFrom(const FileOperateResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.FileOperateResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileOperateResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileOperateResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileOperateResponse::InternalSwap(FileOperateResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileOperateResponse, _impl_.ok_)
      + sizeof(FileOperateResponse::_impl_.ok_)
      - PROTOBUF_FIELD_OFFSET(FileOperateResponse, _impl_.info_)>(
          reinterpret_cast<char*>(&_impl_.info_),
          reinterpret_cast<char*>(&other->_impl_.info_));
}

::google::protobuf::Metadata FileOperateResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[2]);
}
// ===================================================================

class FileSearchRequest::_Internal {
 public:
};

FileSearchRequest::FileSearchRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.FileSearchRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileSearchRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : condition_(arena, from.condition_),
        _cached_size_{0} {}

FileSearchRequest::FileSearchRequest(
    ::google::protobuf::Arena* arena,
    const FileSearchRequest& from)
    : ::google::protobuf::Message(arena) {
  FileSearchRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:MyPackage.FileSearchRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileSearchRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : condition_(arena),
        _cached_size_{0} {}

inline void FileSearchRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FileSearchRequest::~FileSearchRequest() {
  // @@protoc_insertion_point(destructor:MyPackage.FileSearchRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileSearchRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.condition_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileSearchRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.FileSearchRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.condition_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileSearchRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 45, 2> FileSearchRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileSearchRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string condition = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.condition_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string condition = 1;
    {PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.condition_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\11\0\0\0\0\0\0"
    "MyPackage.FileSearchRequest"
    "condition"
  }},
};

::uint8_t* FileSearchRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.FileSearchRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string condition = 1;
  if (!this->_internal_condition().empty()) {
    const std::string& _s = this->_internal_condition();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MyPackage.FileSearchRequest.condition");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.FileSearchRequest)
  return target;
}

::size_t FileSearchRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.FileSearchRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string condition = 1;
  if (!this->_internal_condition().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_condition());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileSearchRequest::_class_data_ = {
    FileSearchRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileSearchRequest::GetClassData() const {
  return &_class_data_;
}

void FileSearchRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileSearchRequest*>(&to_msg);
  auto& from = static_cast<const FileSearchRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.FileSearchRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_condition().empty()) {
    _this->_internal_set_condition(from._internal_condition());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileSearchRequest::CopyFrom(const FileSearchRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.FileSearchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileSearchRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileSearchRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileSearchRequest::InternalSwap(FileSearchRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.condition_, &other->_impl_.condition_, arena);
}

::google::protobuf::Metadata FileSearchRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[3]);
}
// ===================================================================

class FileSearchResponse::_Internal {
 public:
};

FileSearchResponse::FileSearchResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.FileSearchResponse)
}
inline PROTOBUF_NDEBUG_INLINE FileSearchResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : infos_{visibility, arena, from.infos_},
        _cached_size_{0} {}

FileSearchResponse::FileSearchResponse(
    ::google::protobuf::Arena* arena,
    const FileSearchResponse& from)
    : ::google::protobuf::Message(arena) {
  FileSearchResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.ok_ = from._impl_.ok_;

  // @@protoc_insertion_point(copy_constructor:MyPackage.FileSearchResponse)
}
inline PROTOBUF_NDEBUG_INLINE FileSearchResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : infos_{visibility, arena},
        _cached_size_{0} {}

inline void FileSearchResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ok_ = {};
}
FileSearchResponse::~FileSearchResponse() {
  // @@protoc_insertion_point(destructor:MyPackage.FileSearchResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileSearchResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileSearchResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.FileSearchResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.infos_.Clear();
  _impl_.ok_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileSearchResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> FileSearchResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_FileSearchResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool ok = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileSearchResponse, _impl_.ok_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(FileSearchResponse, _impl_.ok_)}},
    // repeated .MyPackage.FileInfo infos = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileSearchResponse, _impl_.infos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .MyPackage.FileInfo infos = 1;
    {PROTOBUF_FIELD_OFFSET(FileSearchResponse, _impl_.infos_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool ok = 2;
    {PROTOBUF_FIELD_OFFSET(FileSearchResponse, _impl_.ok_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }}, {{
    {::_pbi::TcParser::GetTable<::MyPackage::FileInfo>()},
  }}, {{
  }},
};

::uint8_t* FileSearchResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.FileSearchResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .MyPackage.FileInfo infos = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_infos_size()); i < n; i++) {
    const auto& repfield = this->_internal_infos().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // bool ok = 2;
  if (this->_internal_ok() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_ok(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.FileSearchResponse)
  return target;
}

::size_t FileSearchResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.FileSearchResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .MyPackage.FileInfo infos = 1;
  total_size += 1UL * this->_internal_infos_size();
  for (const auto& msg : this->_internal_infos()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // bool ok = 2;
  if (this->_internal_ok() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileSearchResponse::_class_data_ = {
    FileSearchResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileSearchResponse::GetClassData() const {
  return &_class_data_;
}

void FileSearchResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileSearchResponse*>(&to_msg);
  auto& from = static_cast<const FileSearchResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.FileSearchResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_infos()->MergeFrom(
      from._internal_infos());
  if (from._internal_ok() != 0) {
    _this->_internal_set_ok(from._internal_ok());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileSearchResponse::CopyFrom(const FileSearchResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.FileSearchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileSearchResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileSearchResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileSearchResponse::InternalSwap(FileSearchResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.infos_.InternalSwap(&other->_impl_.infos_);
        swap(_impl_.ok_, other->_impl_.ok_);
}

::google::protobuf::Metadata FileSearchResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[4]);
}
// ===================================================================

class FileUploadRequest::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileUploadRequest, _impl_._oneof_case_);
};

FileUploadRequest::FileUploadRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.FileUploadRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileUploadRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : chunk_(arena, from.chunk_),
        size_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

FileUploadRequest::FileUploadRequest(
    ::google::protobuf::Arena* arena,
    const FileUploadRequest& from)
    : ::google::protobuf::Message(arena) {
  FileUploadRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  switch (size_case()) {
    case SIZE_NOT_SET:
      break;
      case kFileSize:
        _impl_.size_.filesize_ = from._impl_.size_.filesize_;
        break;
      case kChunkSize:
        _impl_.size_.chunksize_ = from._impl_.size_.chunksize_;
        break;
  }

  // @@protoc_insertion_point(copy_constructor:MyPackage.FileUploadRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileUploadRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : chunk_(arena),
        size_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void FileUploadRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FileUploadRequest::~FileUploadRequest() {
  // @@protoc_insertion_point(destructor:MyPackage.FileUploadRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileUploadRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.chunk_.Destroy();
  if (has_size()) {
    clear_size();
  }
  _impl_.~Impl_();
}

void FileUploadRequest::clear_size() {
// @@protoc_insertion_point(one_of_clear_start:MyPackage.FileUploadRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (size_case()) {
    case kFileSize: {
      // No need to clear
      break;
    }
    case kChunkSize: {
      // No need to clear
      break;
    }
    case SIZE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = SIZE_NOT_SET;
}


PROTOBUF_NOINLINE void FileUploadRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.FileUploadRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chunk_.ClearToEmpty();
  clear_size();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileUploadRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 0, 0, 2> FileUploadRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileUploadRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes chunk = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(FileUploadRequest, _impl_.chunk_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 fileSize = 1;
    {PROTOBUF_FIELD_OFFSET(FileUploadRequest, _impl_.size_.filesize_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt64)},
    // int64 chunkSize = 2;
    {PROTOBUF_FIELD_OFFSET(FileUploadRequest, _impl_.size_.chunksize_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt64)},
    // bytes chunk = 3;
    {PROTOBUF_FIELD_OFFSET(FileUploadRequest, _impl_.chunk_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* FileUploadRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.FileUploadRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (size_case()) {
    case kFileSize: {
      target = ::google::protobuf::internal::WireFormatLite::
          WriteInt64ToArrayWithField<1>(
              stream, this->_internal_filesize(), target);
      break;
    }
    case kChunkSize: {
      target = ::google::protobuf::internal::WireFormatLite::
          WriteInt64ToArrayWithField<2>(
              stream, this->_internal_chunksize(), target);
      break;
    }
    default:
      break;
  }
  // bytes chunk = 3;
  if (!this->_internal_chunk().empty()) {
    const std::string& _s = this->_internal_chunk();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.FileUploadRequest)
  return target;
}

::size_t FileUploadRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.FileUploadRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes chunk = 3;
  if (!this->_internal_chunk().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_chunk());
  }

  switch (size_case()) {
    // int64 fileSize = 1;
    case kFileSize: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_filesize());
      break;
    }
    // int64 chunkSize = 2;
    case kChunkSize: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_chunksize());
      break;
    }
    case SIZE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileUploadRequest::_class_data_ = {
    FileUploadRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileUploadRequest::GetClassData() const {
  return &_class_data_;
}

void FileUploadRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileUploadRequest*>(&to_msg);
  auto& from = static_cast<const FileUploadRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.FileUploadRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_chunk().empty()) {
    _this->_internal_set_chunk(from._internal_chunk());
  }
  switch (from.size_case()) {
    case kFileSize: {
      _this->_internal_set_filesize(from._internal_filesize());
      break;
    }
    case kChunkSize: {
      _this->_internal_set_chunksize(from._internal_chunksize());
      break;
    }
    case SIZE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileUploadRequest::CopyFrom(const FileUploadRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.FileUploadRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileUploadRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileUploadRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileUploadRequest::InternalSwap(FileUploadRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.chunk_, &other->_impl_.chunk_, arena);
  swap(_impl_.size_, other->_impl_.size_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata FileUploadRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[5]);
}
// ===================================================================

class FileUploadResponse::_Internal {
 public:
};

FileUploadResponse::FileUploadResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.FileUploadResponse)
}
FileUploadResponse::FileUploadResponse(
    ::google::protobuf::Arena* arena, const FileUploadResponse& from)
    : FileUploadResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE FileUploadResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void FileUploadResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.cacheid_ = {};
}
FileUploadResponse::~FileUploadResponse() {
  // @@protoc_insertion_point(destructor:MyPackage.FileUploadResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileUploadResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileUploadResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.FileUploadResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.cacheid_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileUploadResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> FileUploadResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileUploadResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 cacheId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileUploadResponse, _impl_.cacheid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(FileUploadResponse, _impl_.cacheid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 cacheId = 1;
    {PROTOBUF_FIELD_OFFSET(FileUploadResponse, _impl_.cacheid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* FileUploadResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.FileUploadResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 cacheId = 1;
  if (this->_internal_cacheid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_cacheid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.FileUploadResponse)
  return target;
}

::size_t FileUploadResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.FileUploadResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 cacheId = 1;
  if (this->_internal_cacheid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_cacheid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileUploadResponse::_class_data_ = {
    FileUploadResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileUploadResponse::GetClassData() const {
  return &_class_data_;
}

void FileUploadResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileUploadResponse*>(&to_msg);
  auto& from = static_cast<const FileUploadResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.FileUploadResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_cacheid() != 0) {
    _this->_internal_set_cacheid(from._internal_cacheid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileUploadResponse::CopyFrom(const FileUploadResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.FileUploadResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileUploadResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileUploadResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileUploadResponse::InternalSwap(FileUploadResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.cacheid_, other->_impl_.cacheid_);
}

::google::protobuf::Metadata FileUploadResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[6]);
}
// ===================================================================

class FileDownloadRequest::_Internal {
 public:
};

FileDownloadRequest::FileDownloadRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.FileDownloadRequest)
}
FileDownloadRequest::FileDownloadRequest(
    ::google::protobuf::Arena* arena, const FileDownloadRequest& from)
    : FileDownloadRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE FileDownloadRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void FileDownloadRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.fileid_ = {};
}
FileDownloadRequest::~FileDownloadRequest() {
  // @@protoc_insertion_point(destructor:MyPackage.FileDownloadRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileDownloadRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileDownloadRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.FileDownloadRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.fileid_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileDownloadRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> FileDownloadRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileDownloadRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 fileId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileDownloadRequest, _impl_.fileid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(FileDownloadRequest, _impl_.fileid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 fileId = 1;
    {PROTOBUF_FIELD_OFFSET(FileDownloadRequest, _impl_.fileid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* FileDownloadRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.FileDownloadRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 fileId = 1;
  if (this->_internal_fileid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_fileid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.FileDownloadRequest)
  return target;
}

::size_t FileDownloadRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.FileDownloadRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 fileId = 1;
  if (this->_internal_fileid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_fileid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileDownloadRequest::_class_data_ = {
    FileDownloadRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileDownloadRequest::GetClassData() const {
  return &_class_data_;
}

void FileDownloadRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileDownloadRequest*>(&to_msg);
  auto& from = static_cast<const FileDownloadRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.FileDownloadRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_fileid() != 0) {
    _this->_internal_set_fileid(from._internal_fileid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileDownloadRequest::CopyFrom(const FileDownloadRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.FileDownloadRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileDownloadRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileDownloadRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileDownloadRequest::InternalSwap(FileDownloadRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.fileid_, other->_impl_.fileid_);
}

::google::protobuf::Metadata FileDownloadRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[7]);
}
// ===================================================================

class FileDownloadResponse::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::MyPackage::FileDownloadResponse, _impl_._oneof_case_);
};

FileDownloadResponse::FileDownloadResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.FileDownloadResponse)
}
inline PROTOBUF_NDEBUG_INLINE FileDownloadResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : chunk_(arena, from.chunk_),
        size_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

FileDownloadResponse::FileDownloadResponse(
    ::google::protobuf::Arena* arena,
    const FileDownloadResponse& from)
    : ::google::protobuf::Message(arena) {
  FileDownloadResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  switch (size_case()) {
    case SIZE_NOT_SET:
      break;
      case kFileSize:
        _impl_.size_.filesize_ = from._impl_.size_.filesize_;
        break;
      case kChunkSize:
        _impl_.size_.chunksize_ = from._impl_.size_.chunksize_;
        break;
  }

  // @@protoc_insertion_point(copy_constructor:MyPackage.FileDownloadResponse)
}
inline PROTOBUF_NDEBUG_INLINE FileDownloadResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : chunk_(arena),
        size_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void FileDownloadResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FileDownloadResponse::~FileDownloadResponse() {
  // @@protoc_insertion_point(destructor:MyPackage.FileDownloadResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileDownloadResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.chunk_.Destroy();
  if (has_size()) {
    clear_size();
  }
  _impl_.~Impl_();
}

void FileDownloadResponse::clear_size() {
// @@protoc_insertion_point(one_of_clear_start:MyPackage.FileDownloadResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (size_case()) {
    case kFileSize: {
      // No need to clear
      break;
    }
    case kChunkSize: {
      // No need to clear
      break;
    }
    case SIZE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = SIZE_NOT_SET;
}


PROTOBUF_NOINLINE void FileDownloadResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.FileDownloadResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.chunk_.ClearToEmpty();
  clear_size();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileDownloadResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 0, 0, 2> FileDownloadResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileDownloadResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes chunk = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(FileDownloadResponse, _impl_.chunk_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 fileSize = 1;
    {PROTOBUF_FIELD_OFFSET(FileDownloadResponse, _impl_.size_.filesize_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt64)},
    // int64 chunkSize = 2;
    {PROTOBUF_FIELD_OFFSET(FileDownloadResponse, _impl_.size_.chunksize_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt64)},
    // bytes chunk = 3;
    {PROTOBUF_FIELD_OFFSET(FileDownloadResponse, _impl_.chunk_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* FileDownloadResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.FileDownloadResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (size_case()) {
    case kFileSize: {
      target = ::google::protobuf::internal::WireFormatLite::
          WriteInt64ToArrayWithField<1>(
              stream, this->_internal_filesize(), target);
      break;
    }
    case kChunkSize: {
      target = ::google::protobuf::internal::WireFormatLite::
          WriteInt64ToArrayWithField<2>(
              stream, this->_internal_chunksize(), target);
      break;
    }
    default:
      break;
  }
  // bytes chunk = 3;
  if (!this->_internal_chunk().empty()) {
    const std::string& _s = this->_internal_chunk();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.FileDownloadResponse)
  return target;
}

::size_t FileDownloadResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.FileDownloadResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes chunk = 3;
  if (!this->_internal_chunk().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_chunk());
  }

  switch (size_case()) {
    // int64 fileSize = 1;
    case kFileSize: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_filesize());
      break;
    }
    // int64 chunkSize = 2;
    case kChunkSize: {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_chunksize());
      break;
    }
    case SIZE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileDownloadResponse::_class_data_ = {
    FileDownloadResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileDownloadResponse::GetClassData() const {
  return &_class_data_;
}

void FileDownloadResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileDownloadResponse*>(&to_msg);
  auto& from = static_cast<const FileDownloadResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.FileDownloadResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_chunk().empty()) {
    _this->_internal_set_chunk(from._internal_chunk());
  }
  switch (from.size_case()) {
    case kFileSize: {
      _this->_internal_set_filesize(from._internal_filesize());
      break;
    }
    case kChunkSize: {
      _this->_internal_set_chunksize(from._internal_chunksize());
      break;
    }
    case SIZE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileDownloadResponse::CopyFrom(const FileDownloadResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.FileDownloadResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileDownloadResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileDownloadResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileDownloadResponse::InternalSwap(FileDownloadResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.chunk_, &other->_impl_.chunk_, arena);
  swap(_impl_.size_, other->_impl_.size_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata FileDownloadResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[8]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace MyPackage
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
